# Generated by Django 2.2.1 on 2019-05-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bolsa.Pregao'),
        ),
    ]
