# Generated by Django 2.2.1 on 2019-05-19 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_auto_20190518_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='acao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolsa.Pregao'),
            preserve_default=False,
        ),
    ]
